[package]
name = "resource_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
async-trait = "0.1.83"
crossbeam = "0.8.4"
crossbeam-channel = "0.5"